
language: objective-c  #1
osx_image: xcode8.3 #2
xcode_workspace: Example/EPShapes.xcworkspace #3
xcode_scheme: EPShapes #4
xcode_sdk: iphonesimulator #5

script:
- DESTINATION="-destination \"platform=iOS Simulator,name=iPhone 7,OS=latest\""
- COMMAND="xcodebuild -workspace \"$TRAVIS_XCODE_WORKSPACE\" -scheme \"$TRAVIS_XCODE_SCHEME\" $DESTINATION"
- eval $COMMAND clean build &>/dev/null
- set -o pipefail
- eval $COMMAND test | xcpretty

#https://github.com/ipraba/EPSignature
